{% set name = "py-cord" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py-cord-{{ version }}.tar.gz
  sha256: 43149040431c0bc13dfc12685d5e636c15f1b9ecba2d162ecb6b22d66b3e5684

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiohttp >=3.6.0,<3.9.0
    - python >=3.6

test:
  imports:
    - discord
    - discord.ext.commands
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Pycord-Development/pycord
  summary: A Python wrapper for the Discord API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
